version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean package
      - echo Building the Docker image...
      - docker build -t sharadrajore/myapp:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker login -u sharadrajore -p seed_9096311380
      - docker push sharadrajore/myapp:latest
