version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk17
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo docker login -u sharadrajore -p seed_9096311380
  build:
    commands:
      - echo Building the Spring Boot application...
      - ./mvnw clean package -DskipTests=true
      - echo Building the Docker image...
      - docker build -t sharadrajore/myapp:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker push sharadrajore/myapp:latest
